### ISSUE TITLE
Polish culture 

### ISSUE THREAD

**Issue by Klamos** [hmlendea/more-cultural-names#111]
Hi, I would like to make some corrections, add new and delete duplicates of Polish culture names of cities and titles.

**Comment by hmlendea** [comment]
Hello,

Your involvement would be very welcome!

You can either make the changes yourself if you're comfortable with it (forking this repo, and making a PR), or you can send me _(e.g. in this thread)_ what needs to be changed and I'll add the changes myself.

**Comment by Klamos** [comment]
I would be very thankful if you tell me more about making own repo.

**Comment by hmlendea** [comment]
Closed old issue.
