### ISSUE TITLE
Not working, even when I don't have any other mods enabled.

### ISSUE THREAD

**Issue by makslaskabata2** [hmlendea/more-cultural-names#148]
Using the Paradox Plaza mod.

MCN doesn't work at all. Before it used to work just fine. (when I was using 1.3.3)

**Comment by hmlendea** [comment]
Hi,

What exactly is not working? Does the game crash or are the names simply not showing up? Also, which edition are you using? (vanilla, IBL, MB+)

I have updated the mods on Paradox Mods as they were quite out-of-date compared to the other stores, try updating it and see if it helps.

**Comment by hmlendea** [comment]
Closed the issue for inactivity
