### ISSUE TITLE
Unsupported Diacritic

### ISSUE THREAD

**Issue by Linxuski** [hmlendea/more-cultural-names#162]
Hi!

I noticed that 'al-H̱ānīa' wasn't displayed properly in game:
![1](https://user-images.githubusercontent.com/50371587/151910803-674de004-9f36-42fa-a2c8-bb9e8c652a6d.png)

Not sure what you can do to fix it as even the extended vanilla font looks odd with it:
![2](https://user-images.githubusercontent.com/50371587/151910873-6abd6a01-d93d-4082-a4d8-bf7e9fc45d23.png)

I guess all you could do is replace all instances of 'H̱' with 'H'?

**Comment by hmlendea** [comment]
Hello

Thanks for the report!

It will be fixed in the next version.
