### ISSUE TITLE
Issue with Sinews of War

### ISSUE THREAD

**Issue by CactusPunch** [hmlendea/more-cultural-names#190]
With both mods-enabled the county of Brysis is its own county, where in Sinews of War it's part of Constantinople. This breaks Constantinople as it doesn't have enough food, also the county of Brysis is bugged with 0 population.

**Comment by hmlendea** [comment]
Hi.

Thanks for reporting this.

Looks like Sinews of War started editing the landed_titles file again, which makes it incompatible with MCN.
I will revive the compatibility patch between MCN and SoW. I'm working on it right now so it will be ready soon.
