### ISSUE TITLE
Latest CK3 mod version (v22.172.0) is not backwards compatible with v1.6.0.1<=

### ISSUE THREAD

**Issue by robinlahtinen** [hmlendea/more-cultural-names#235]
For example CK3 v1.6.1 added the Guanche Culture which data is not available on previous versions. Doesn't cause crashes from my testing, but causes missing translations/strings.

**Proposed fix:**

Edit descriptor.mod supported_version to "1.6.1.*" or with proper semantic versioning restrictions and lack of better versioning syntax "1.6.1".

**Comment by hmlendea** [comment]
Agreed.
I will update the version string and it will be included in the next release.
Thanks for pointing this out!
