### ISSUE TITLE
[Imperator: Invictus version] Invisible character in the Punic name of the territory of Carthage

### ISSUE THREAD

**Issue by Phalanx1** [hmlendea/more-cultural-names#276]
The title is self-explanatory. What should, I assume, be Ḥ or something similar is instead empty in some places of the UI and a rectangle in others.

**Comment by hmlendea** [comment]
Thanks.

This actually needs to be solved in [hmlendea/more-cultural-names-builder](https://github.com/hmlendea/more-cultural-names-builder/issues/new)

This will be fixed for the next MCN release.

Thanks for reporting it!

**Comment by hmlendea** [comment]
Fixed. The new release will be coming shortly.
