### ISSUE TITLE
Brythonic naming for e_Brittania

### ISSUE THREAD

**Issue by singitformehal** [hmlendea/more-cultural-names#48]
I noticed the only name variation for the Empire of Brittania for both Brythonic and Goidellic cultures is "Cruithn".

Firstly this is modern Irish, the period correct spelling would be "Cruthin" for Old Irish or "Cruithnig/Cruithni" for Middle Irish. 

Secondly this word is only fitting for the Irish and Gaelic cultures. Here are some proposed alternatives for the other cultures in the Brythonic group.

Prydain (old welsh) can technically be used for all of them or Ynys Prydein (middle) specifically for Wales. Alternatively Pritani is the original Brittonic Celtic word but for the sake of variation could be used for Pictish, Cornish and Breton only. Additionally the original game variations of Pictavia and Alba might be used;

Welsh - Prydain
Cornish - Prydain
Breton - Pritani
Cumbrian - Pritani
Pictish - Pictavia
Gaelic - Alban
Irish - Cruthin

Lastly I also noticed there is no Anglo-Saxon entry. Alfred the Great translated "Orosius' Seven Books of History Against the Pagan" and used the term "Bryttania" so I feel this would be appropriate.

**Comment by hmlendea** [comment]
Thank you very much for this. This is really useful information!
I will try to implement these as soon as I can

**Comment by singitformehal** [comment]
No problem, thanks for the awesome mod!

**Comment by hmlendea** [comment]
This has already been addressed in a past release
