### ISSUE TITLE
Add examples of names to the readme and Steam descriptions

### ISSUE THREAD

**Issue by Thunderforge** [hmlendea/more-cultural-names#65]
Right now, the readme doesn't include any examples of what sort of names are included and how the experience differs from the base game. This makes it very difficult for a user to decide if the mod is something they want to install.

Please add some examples of how the game changes with this mod so the user can decide if adding "65 thousand names for over 450 languages, settings and time periods" is something they want.

**Comment by hmlendea** [comment]
Hi,

Yeah, I was to upload screenshots to showcase different regions under different cultures, but I never got around doing it.

I'm going to do this once the next update is out though, for all of the supported games. (Well, maybe not yet for Imperator, due to a variety of reasons)

**Comment by hmlendea** [comment]
I've uploaded some quite diverse screenshots and more will come later on
