### ISSUE TITLE
Question/collaboration

### ISSUE THREAD

**Issue by IohannesIohannium** [hmlendea/more-cultural-names#88]
Hello, would it be possible for your CK3 build to be integrated with the I:R-CK3 converter project (https://github.com/paradoxGameConverters/ImperatorToCK3) and if yes could we add a section of the name database for the I:R cultures added in CK3?

**Comment by hmlendea** [comment]
Hmmm I'm not too familiar with this.

Is it generating its own landed_titles file, or does it use the vanilla CK3 one?
If it's the vanilla one then MCN will already be compatible (though any new cultures will obviously be unlocalised). If not then it's tricky.

**Comment by IohannesIohannium** [comment]
It does not generate its own landed_titles, so your build is already compatible; but since we're adding new cultures (e.g. Gaulish, Carthaginian, Dacian), maybe we could add names for those in your database.

**Comment by hmlendea** [comment]
Adding those names would be really cool
I already have some of them as the same DB is also used for `Imperator: Rome` so adding more would benefit both I:R and the converted CK3 save

Though I will need to take a further look at what exactly needs to change to support the save-conversion mod
